// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEMOtQcopjPLcUGceD4S9qst7f2WKjaA',
    appId: '1:738692737688:web:e9b20c27017a1d1a0a7eed',
    messagingSenderId: '738692737688',
    projectId: 'fluttertask-7cd00',
    authDomain: 'fluttertask-7cd00.firebaseapp.com',
    storageBucket: 'fluttertask-7cd00.firebasestorage.app',
    measurementId: 'G-F7G8XGJDQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzY1uKBTqEumqj0px4ceBE-YvaAXErh3U',
    appId: '1:738692737688:android:7eb2f96ec63ec9990a7eed',
    messagingSenderId: '738692737688',
    projectId: 'fluttertask-7cd00',
    storageBucket: 'fluttertask-7cd00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2oRXiPDADwhL0MlcUXBkUOC-ocH0xflY',
    appId: '1:738692737688:ios:da446935f2699ccc0a7eed',
    messagingSenderId: '738692737688',
    projectId: 'fluttertask-7cd00',
    storageBucket: 'fluttertask-7cd00.firebasestorage.app',
    iosBundleId: 'com.example.fluttertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2oRXiPDADwhL0MlcUXBkUOC-ocH0xflY',
    appId: '1:738692737688:ios:da446935f2699ccc0a7eed',
    messagingSenderId: '738692737688',
    projectId: 'fluttertask-7cd00',
    storageBucket: 'fluttertask-7cd00.firebasestorage.app',
    iosBundleId: 'com.example.fluttertask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAEMOtQcopjPLcUGceD4S9qst7f2WKjaA',
    appId: '1:738692737688:web:9cee03ac8eedd8470a7eed',
    messagingSenderId: '738692737688',
    projectId: 'fluttertask-7cd00',
    authDomain: 'fluttertask-7cd00.firebaseapp.com',
    storageBucket: 'fluttertask-7cd00.firebasestorage.app',
    measurementId: 'G-VGKZ20GP41',
  );
}
